#!/bin/bash

_puid=$(printenv PUID)
_pgid=$(printenv PGID)

cloud_encrypt_dir="/cloud-encrypt"
cloud_decrypt_dir="/cloud-decrypt"

local_media_dir="/local-media"
local_encrypt_dir="/local-encrypt"
local_union_dir="/union"

encfs_mount_options="-o allow_other,nonempty"

ufs_options="-o uid=${_puid:-911} -o gid=${_pgid:-911} -o cow,allow_other,direct_io,atomic_o_trunc,large_read,default_permissions"

log_dir="/log"
if [ ! -d "${log_dir}" ]; then
	mkdir -p "${log_dir}"
fi
